// Generated by tools/ghidra/ExportHeader.java -- do not edit.
#pragma once
#pragma pack(push, 1)
struct Book;
struct Button;
struct CArchive;
struct CString;
struct DecompressImageInfo;
struct FontGlyphs;
struct GXDisplayProperties;
struct GXKeyList;
struct Game;
struct GameObj;
struct GameState;
struct Glyph;
struct HBRUSH__;
struct HDC__;
struct HICON__;
struct HINSTANCE__;
struct HKEY__;
struct HMENU__;
struct HWND__;
struct ImgRect;
struct Inventory;
struct ItemRect;
struct Line;
struct Link;
struct Menu;
struct MenuButton;
struct Point;
struct PopupMenu;
struct Rec0c;
struct Rec14;
struct Rec15c;
struct Rec44;
struct Rec9;
struct Rec9ec;
struct RecE1;
struct RecF8;
struct RecList;
struct RecNode;
struct Scene;
struct Screen;
struct ScriptOp;
struct ScriptOpList;
struct StrItem;
struct StrList;
struct StrNode;
struct TextList;
struct Tm;
struct Zoom;
struct _OVERLAPPED;
struct _SECURITY_ATTRIBUTES;
struct _div_t;
struct _struct_519;
struct tagMSG;
struct tagPAINTSTRUCT;
struct tagPOINT;
struct tagRECT;
struct tagWNDCLASSW;
union _union_518;
struct MenuButton {
  P32<void> imgs[6];
  ushort x;
  ushort y;
  ushort w;
  ushort h;
  int imgH;
  int imgW;
  byte hasImg0;
  byte hasImg1;
  byte hasImg5;
  byte state;
  byte savedState;
  uint8_t field_0x2d[3];
  int id;
};
static_assert(sizeof(MenuButton) == 52, "MenuButton");
struct RecNode {
  P32<RecNode> next;
  P32<RecNode> prev;
  MenuButton item;
};
static_assert(sizeof(RecNode) == 60, "RecNode");
struct RecList {
  P32<void> vtbl;
  P32<RecNode> head;
  P32<RecNode> tail;
  int count;
  P32<RecNode> free;
  P32<void> blocks;
  int blockSize;
};
static_assert(sizeof(RecList) == 28, "RecList");
typedef long LONG;
typedef LONG LSTATUS;
struct ImgRect {
  P32<ushort> pixels;
  int x;
  int y;
  int w;
  int h;
};
static_assert(sizeof(ImgRect) == 20, "ImgRect");
struct CString {
  P32<wchar16> str;
};
static_assert(sizeof(CString) == 4, "CString");
struct Rec14 {
  CString label;
  byte enabled;
  uint8_t field_0x5[3];
  CString text;
  uint kind;
  byte arg;
  byte b11;
  byte b12;
  uint8_t field_0x13[1];
};
static_assert(sizeof(Rec14) == 20, "Rec14");
struct ScriptOp {
  int op;
  byte b4;
  uint8_t field_0x5[1];
  ushort arg;
  ushort arg2;
  byte ba;
  byte bb;
  byte bc;
  byte bd;
  uint8_t field_0xe[2];
  int i10;
  byte b14;
  byte list[8];
  uint8_t field_0x1d[3];
  CString str[3];
};
static_assert(sizeof(ScriptOp) == 44, "ScriptOp");
struct ScriptOpList {
  ScriptOp ops[25];
  int count;
};
static_assert(sizeof(ScriptOpList) == 1104, "ScriptOpList");
struct Link {
  ushort id;
  byte script;
  byte f3;
};
static_assert(sizeof(Link) == 4, "Link");
struct GameObj {
  ImgRect icon;
  CString name;
  byte id;
  byte nSubs;
  byte selected;
  uint8_t field_0x1b[1];
  Rec14 subs[8];
  byte fbc;
  uint8_t field_0xbd[3];
  ScriptOpList scripts[30];
  Link link;
  int f8224;
};
static_assert(sizeof(GameObj) == 33320, "GameObj");
struct Rec9 {
  byte flags[9];
};
static_assert(sizeof(Rec9) == 9, "Rec9");
struct RecE1 {
  Rec9 objStates[25];
};
static_assert(sizeof(RecE1) == 225, "RecE1");
struct Rec9ec {
  byte f0;
  byte flags[8];
  uint8_t field_0x9[3];
  CString name;
  byte f10;
  byte f11;
  Rec9 objStates[30];
  RecE1 recsE1[10];
  uint8_t field_0x9ea[2];
};
static_assert(sizeof(Rec9ec) == 2540, "Rec9ec");
typedef uint UINT_PTR;
typedef UINT_PTR WPARAM;
typedef ulong DWORD;
typedef P32<DWORD> LPDWORD;
struct Screen {
  int f0;
  int pixFmt;
  int w;
  int h;
  int xPitch;
  int yPitch;
  int size;
  P32<ushort> layer[5];
};
static_assert(sizeof(Screen) == 48, "Screen");
struct StrItem {
  CString text;
  int val;
  byte flag;
  uint8_t field_0x9[3];
};
static_assert(sizeof(StrItem) == 12, "StrItem");
struct StrNode {
  P32<StrNode> next;
  P32<StrNode> prev;
  StrItem item;
};
static_assert(sizeof(StrNode) == 20, "StrNode");
struct StrList {
  P32<void> vtbl;
  P32<StrNode> head;
  P32<StrNode> tail;
  int count;
  P32<StrNode> free;
  P32<void> blocks;
  int blockSize;
};
static_assert(sizeof(StrList) == 28, "StrList");
struct Glyph {
  byte w;
  byte h;
  uint8_t field_0x2[2];
  P32<ushort> pixels;
  P32<Screen> screen;
  byte keyed;
  byte loaded;
  uint8_t field_0xe[2];
};
static_assert(sizeof(Glyph) == 16, "Glyph");
struct FontGlyphs {
  Glyph glyphs[255];
};
static_assert(sizeof(FontGlyphs) == 4080, "FontGlyphs");
struct TextList {
  P32<void> img;
  int w;
  int h;
  P32<Screen> screen;
  StrList lines;
  byte top;
  byte page;
  byte count;
  uint8_t field_0x2f[1];
  int x;
  int right;
  int top_y;
  int bottom;
  byte hasText;
  uint8_t field_0x41[3];
  P32<FontGlyphs> font;
};
static_assert(sizeof(TextList) == 72, "TextList");
struct GXKeyList {
  short vkUp;
  short _p0;
  int ptUp[2];
  short vkDown;
  short _p1;
  int ptDown[2];
  short vkLeft;
  short _p2;
  int ptLeft[2];
  short vkRight;
  short _p3;
  int ptRight[2];
  short vkA;
  short _p4;
  int ptA[2];
  short vkB;
  short _p5;
  int ptB[2];
  short vkC;
  short _p6;
  int ptC[2];
  short vkStart;
  short _p7;
  int ptStart[2];
};
static_assert(sizeof(GXKeyList) == 96, "GXKeyList");
struct RecF8 {
  CString name;
  byte f4;
  byte noSprite;
  byte f6;
  uint8_t field_0x7[1];
  CString spritePath;
  int x;
  int y;
  int poly[8];
  uint8_t field_0x34[8];
  byte visible;
  uint8_t field_0x3d[3];
  ImgRect img;
  byte nActions;
  uint8_t field_0x55[3];
  Rec14 actions[8];
};
static_assert(sizeof(RecF8) == 248, "RecF8");
struct Rec0c {
  int val;
  byte b4;
  byte b5;
  uint8_t field_0x6[2];
  CString text;
};
static_assert(sizeof(Rec0c) == 12, "Rec0c");
struct Button {
  P32<void> img;
  P32<void> imgDown;
  int x;
  int y;
  int w;
  int h;
  byte state;
  uint8_t field_0x19[3];
  P32<Screen> screen;
  int f20;
};
static_assert(sizeof(Button) == 36, "Button");
struct Book {
  byte flags[77];
  uint8_t field_0x4d[3];
  CString text[77];
  byte pageLen[7];
  byte curPage;
};
static_assert(sizeof(Book) == 396, "Book");
typedef uchar BYTE;
struct Tm {
  int sec;
  int min;
  int hour;
  int mday;
  int mon;
  int year;
  int wday;
  int yday;
  int isdst;
};
static_assert(sizeof(Tm) == 36, "Tm");
typedef P32<void> LPVOID;
typedef int BOOL;
struct _SECURITY_ATTRIBUTES {
  DWORD nLength;
  LPVOID lpSecurityDescriptor;
  BOOL bInheritHandle;
};
static_assert(sizeof(_SECURITY_ATTRIBUTES) == 12, "_SECURITY_ATTRIBUTES");
typedef P32<_SECURITY_ATTRIBUTES> LPSECURITY_ATTRIBUTES;
struct HINSTANCE__ {
  int unused;
};
static_assert(sizeof(HINSTANCE__) == 4, "HINSTANCE__");
typedef P32<HINSTANCE__> HINSTANCE;
struct HWND__ {
  int unused;
};
static_assert(sizeof(HWND__) == 4, "HWND__");
typedef P32<HWND__> HWND;
typedef uint UINT;
typedef P32<void> WNDPROC;
struct HICON__ {
  int unused;
};
static_assert(sizeof(HICON__) == 4, "HICON__");
typedef P32<HICON__> HICON;
typedef HICON HCURSOR;
struct HBRUSH__ {
  int unused;
};
static_assert(sizeof(HBRUSH__) == 4, "HBRUSH__");
typedef P32<HBRUSH__> HBRUSH;
typedef wchar16 WCHAR;
typedef P32<WCHAR> LPCWSTR;
struct tagWNDCLASSW {
  UINT style;
  WNDPROC lpfnWndProc;
  int cbClsExtra;
  int cbWndExtra;
  HINSTANCE hInstance;
  HICON hIcon;
  HCURSOR hCursor;
  HBRUSH hbrBackground;
  LPCWSTR lpszMenuName;
  LPCWSTR lpszClassName;
};
static_assert(sizeof(tagWNDCLASSW) == 40, "tagWNDCLASSW");
typedef tagWNDCLASSW WNDCLASSW;
struct Rec44 {
  CString text;
  Rec0c replies[5];
  byte active;
  uint8_t field_0x41[3];
};
static_assert(sizeof(Rec44) == 68, "Rec44");
struct Rec15c {
  CString title;
  byte count;
  byte script;
  uint8_t field_0x6[2];
  Rec44 choices[5];
};
static_assert(sizeof(Rec15c) == 348, "Rec15c");
struct Zoom {
  byte count;
  byte slot;
  uint8_t field_0x2[2];
  CString path;
  uint8_t field_0x8[8];
  ImgRect img;
  byte loaded;
  uint8_t field_0x25[3];
  RecF8 recs[25];
};
static_assert(sizeof(Zoom) == 6240, "Zoom");
struct Scene {
  uint8_t field_0x0[8];
  int kind;
  ImgRect bg;
  CString strs[3];
  byte curStr;
  uint8_t field_0x2d[3];
  Rec15c topics[5];
  uint8_t field_0x6fc[3480];
  byte f1494;
  uint8_t field_0x1495[3];
  RecF8 objs[30];
  byte nObjs;
  uint8_t field_0x31a9[3];
  Zoom zooms[10];
  byte nExits;
  uint8_t field_0x1256d[1];
  Link exits[10];
  byte f12596[7];
  uint8_t field_0x1259d[3];
  ScriptOpList scripts[30];
  int nScripts;
};
static_assert(sizeof(Scene) == 108292, "Scene");
struct Line {
  float m;
  float b;
  byte vertical;
  byte horizontal;
  uint8_t field_0xa[2];
};
static_assert(sizeof(Line) == 12, "Line");
struct Inventory {
  byte count;
  byte selected;
  uint8_t field_0x2[2];
  GameObj objs[40];
};
static_assert(sizeof(Inventory) == 1332804, "Inventory");
struct GameState {
  Rec9ec scenes[450];
  Inventory inventory;
  Book book;
  ImgRect panelAnim[8];
  ushort curScene;
  uint8_t field_0x25c94a[2];
  uint playTime;
  uint lastTime;
};
static_assert(sizeof(GameState) == 2476372, "GameState");
struct ItemRect {
  byte hilite;
  uint8_t field_0x1[3];
  int x;
  int y;
  int w;
  int h;
};
static_assert(sizeof(ItemRect) == 20, "ItemRect");
struct PopupMenu {
  P32<Screen> screen;
  P32<FontGlyphs> font;
  P32<FontGlyphs> font2;
  byte fc;
  uint8_t field_0xd[1];
  ushort posX;
  ushort f10;
  ushort posY;
  ushort f14;
  uint8_t field_0x16[2];
  int left;
  int top;
  int itemW;
  int itemH;
  CString items[15];
  byte count;
  uint8_t field_0x65[3];
  P32<ushort> saved;
  ItemRect itemRects[15];
};
static_assert(sizeof(PopupMenu) == 408, "PopupMenu");
struct Game {
  ImgRect frame;
  ImgRect bg;
  ImgRect overlay;
  ImgRect zoom;
  Button buttons[6];
  P32<Screen> screen;
  CString descStr;
  CString statusStr;
  CString invStr;
  CString str138;
  TextList desc;
  TextList status;
  TextList inv;
  byte invSel;
  uint8_t field_0x215[3];
  P32<FontGlyphs> descFont;
  P32<FontGlyphs> titleFont;
  P32<FontGlyphs> hiFont;
  P32<FontGlyphs> font;
  P32<FontGlyphs> font2;
  byte f22c;
  byte f22d;
  ushort dlgTopic;
  byte f230[6];
  uint8_t field_0x236[2];
  CString str238;
  Scene scene;
  P32<GameState> state;
  byte dlgState;
  byte dlgSel;
  uint8_t field_0x1a946[2];
  PopupMenu popup;
};
static_assert(sizeof(Game) == 109280, "Game");
typedef P32<BYTE> LPBYTE;
typedef P32<void> HANDLE;
struct HMENU__ {
  int unused;
};
static_assert(sizeof(HMENU__) == 4, "HMENU__");
typedef P32<HMENU__> HMENU;
typedef P32<LONG> PLONG;
typedef ushort WORD;
typedef WORD ATOM;
typedef long LONG_PTR;
typedef LONG_PTR LRESULT;
struct HKEY__ {
  int unused;
};
static_assert(sizeof(HKEY__) == 4, "HKEY__");
typedef P32<HKEY__> HKEY;
typedef ulong ULONG_PTR;
struct _struct_519 {
  DWORD Offset;
  DWORD OffsetHigh;
};
static_assert(sizeof(_struct_519) == 8, "_struct_519");
typedef P32<void> PVOID;
union _union_518 {
  _struct_519 s;
  PVOID Pointer;
};
static_assert(sizeof(_union_518) == 8, "_union_518");
struct _OVERLAPPED {
  ULONG_PTR Internal;
  ULONG_PTR InternalHigh;
  _union_518 u;
  HANDLE hEvent;
};
static_assert(sizeof(_OVERLAPPED) == 20, "_OVERLAPPED");
typedef P32<_OVERLAPPED> LPOVERLAPPED;
struct Menu {
  P32<ushort> img;
  ushort x;
  ushort y;
  int w;
  int h;
  byte hasImg;
  byte active;
  uint8_t field_0x12[2];
  P32<ushort> img2;
  uint8_t field_0x18[8];
  int img2W;
  int img2H;
  P32<Glyph> font;
  PopupMenu popup;
  RecList buttons;
  P32<Screen> screen;
};
static_assert(sizeof(Menu) == 484, "Menu");
typedef LONG_PTR LPARAM;
struct tagPOINT {
  LONG x;
  LONG y;
};
static_assert(sizeof(tagPOINT) == 8, "tagPOINT");
typedef tagPOINT POINT;
struct tagMSG {
  HWND hwnd;
  UINT message;
  WPARAM wParam;
  LPARAM lParam;
  DWORD time;
  POINT pt;
};
static_assert(sizeof(tagMSG) == 28, "tagMSG");
typedef tagMSG MSG;
struct GXDisplayProperties {
  uint cxWidth;
  uint cyHeight;
  int cbxPitch;
  int cbyPitch;
  int cBPP;
  uint ffFormat;
};
static_assert(sizeof(GXDisplayProperties) == 24, "GXDisplayProperties");
struct Point {
  int x;
  int y;
};
static_assert(sizeof(Point) == 8, "Point");
struct CArchive {
  uint8_t field_0x0[20];
  uint mode;
  uint8_t field_0x18[12];
  P32<byte> cur;
  P32<byte> max;
  uint8_t field_0x2c[4];
};
static_assert(sizeof(CArchive) == 48, "CArchive");
struct _div_t {
  int quot;
  int rem;
};
static_assert(sizeof(_div_t) == 8, "_div_t");
typedef _div_t div_t;
struct HDC__ {
  int unused;
};
static_assert(sizeof(HDC__) == 4, "HDC__");
typedef P32<HDC__> HDC;
struct tagRECT {
  LONG left;
  LONG top;
  LONG right;
  LONG bottom;
};
static_assert(sizeof(tagRECT) == 16, "tagRECT");
typedef tagRECT RECT;
struct tagPAINTSTRUCT {
  HDC hdc;
  BOOL fErase;
  RECT rcPaint;
  BOOL fRestore;
  BOOL fIncUpdate;
  BYTE rgbReserved[32];
};
static_assert(sizeof(tagPAINTSTRUCT) == 64, "tagPAINTSTRUCT");
struct DecompressImageInfo {
  uint dwSize;
  P32<void> pbBuffer;
  uint dwBufferMax;
  uint dwBufferCurrent;
  P32<void> phBM;
  P32<void> ppImageRender;
  int iBitDepth;
  int lParam;
  P32<void> hdc;
  int iScale;
  int iMaxWidth;
  int iMaxHeight;
  P32<void> pfnGetData;
  P32<void> pfnImageProgress;
  uint crTransparentOverride;
};
static_assert(sizeof(DecompressImageInfo) == 60, "DecompressImageInfo");
#pragma pack(pop)
typedef undefined4 T_DAT_0025c8b0;
#define DAT_0025c8b0 (*(T_DAT_0025c8b0 *)(uintptr_t)0x0025c8b0)
typedef undefined4 T_g_afxEmptyString;
#define g_afxEmptyString (*(T_g_afxEmptyString *)(uintptr_t)0x00043ea0)
typedef char T_g_animFrame;
#define g_animFrame (*(T_g_animFrame *)(uintptr_t)0x002dc3f0)
typedef undefined4 T_g_animTimer;
#define g_animTimer (*(T_g_animTimer *)(uintptr_t)0x00048680)
typedef undefined1 T_g_cheat1Idx;
#define g_cheat1Idx (*(T_g_cheat1Idx *)(uintptr_t)0x00047688)
typedef ushort T_g_cheat1Keys[8];
#define g_cheat1Keys (*(T_g_cheat1Keys *)(uintptr_t)0x000444b8)
typedef undefined1 T_g_cheat2Idx;
#define g_cheat2Idx (*(T_g_cheat2Idx *)(uintptr_t)0x000444a4)
typedef ushort T_g_cheat2Keys[8];
#define g_cheat2Keys (*(T_g_cheat2Keys *)(uintptr_t)0x000444a8)
typedef ushort T_g_colorKey;
#define g_colorKey (*(T_g_colorKey *)(uintptr_t)0x002dc3ec)
typedef undefined4 T_g_emptyA;
#define g_emptyA (*(T_g_emptyA *)(uintptr_t)0x002dc3f8)
typedef undefined1 T_g_emptyW;
#define g_emptyW (*(T_g_emptyW *)(uintptr_t)0x002dc3f4)
typedef byte T_g_fadeActive;
#define g_fadeActive (*(T_g_fadeActive *)(uintptr_t)0x002dc3a8)
typedef ImgRect T_g_fadeFx[6];
#define g_fadeFx (*(T_g_fadeFx *)(uintptr_t)0x002dc328)
typedef FontGlyphs T_g_fontPopupOrange;
#define g_fontPopupOrange (*(T_g_fontPopupOrange *)(uintptr_t)0x00047690)
typedef FontGlyphs T_g_fontPopupWhite;
#define g_fontPopupWhite (*(T_g_fontPopupWhite *)(uintptr_t)0x000444c8)
typedef FontGlyphs T_g_fontTextBlack;
#define g_fontTextBlack (*(T_g_fontTextBlack *)(uintptr_t)0x00063178)
typedef FontGlyphs T_g_fontTextBlue;
#define g_fontTextBlue (*(T_g_fontTextBlue *)(uintptr_t)0x002db338)
typedef FontGlyphs T_g_fontTextWhite;
#define g_fontTextWhite (*(T_g_fontTextWhite *)(uintptr_t)0x000464b0)
typedef FontGlyphs T_g_fontTextYellow;
#define g_fontTextYellow (*(T_g_fontTextYellow *)(uintptr_t)0x000454b8)
typedef Game T_g_game;
#define g_game (*(T_g_game *)(uintptr_t)0x00048698)
typedef byte T_g_gameFinished;
#define g_gameFinished (*(T_g_gameFinished *)(uintptr_t)0x002db2fc)
typedef undefined4 T_g_gameState;
#define g_gameState (*(T_g_gameState *)(uintptr_t)0x00064168)
typedef short T_g_gamma;
#define g_gamma (*(T_g_gamma *)(uintptr_t)0x000464a8)
typedef byte T_g_glowActive;
#define g_glowActive (*(T_g_glowActive *)(uintptr_t)0x002dc3a4)
typedef char T_g_glowDir;
#define g_glowDir (*(T_g_glowDir *)(uintptr_t)0x00043428)
typedef ImgRect T_g_glowFx[6];
#define g_glowFx (*(T_g_glowFx *)(uintptr_t)0x002c0b38)
typedef GXDisplayProperties T_g_gxProps;
#define g_gxProps (*(T_g_gxProps *)(uintptr_t)0x002c0ac0)
typedef undefined4 T_g_hwnd;
#define g_hwnd (*(T_g_hwnd *)(uintptr_t)0x00047684)
typedef DecompressImageInfo T_g_imgDecompInfo;
#define g_imgDecompInfo (*(T_g_imgDecompInfo *)(uintptr_t)0x002dc3b0)
typedef undefined1 T_g_inGame;
#define g_inGame (*(T_g_inGame *)(uintptr_t)0x00048688)
typedef undefined1 T_g_initFlag;
#define g_initFlag (*(T_g_initFlag *)(uintptr_t)0x000444a0)
typedef CString T_g_installDir;
#define g_installDir (*(T_g_installDir *)(uintptr_t)0x0004768c)
typedef GXKeyList T_g_keys;
#define g_keys (*(T_g_keys *)(uintptr_t)0x002c0ad8)
typedef ImgRect T_g_logos[6];
#define g_logos (*(T_g_logos *)(uintptr_t)0x002c0a10)
typedef Menu T_g_menu;
#define g_menu (*(T_g_menu *)(uintptr_t)0x000474a0)
typedef P32<void> T_g_monthNames[12];
#define g_monthNames (*(T_g_monthNames *)(uintptr_t)0x000433f4)
typedef int T_g_pixelFormat;
#define g_pixelFormat (*(T_g_pixelFormat *)(uintptr_t)0x0004868c)
typedef ImgRect T_g_progressBar;
#define g_progressBar (*(T_g_progressBar *)(uintptr_t)0x002db308)
typedef ImgRect T_g_progressFill;
#define g_progressFill (*(T_g_progressFill *)(uintptr_t)0x002db2e8)
typedef Scene T_g_scratchScene;
#define g_scratchScene (*(T_g_scratchScene *)(uintptr_t)0x002c0bb0)
typedef byte T_g_scratchSceneGuard;
#define g_scratchSceneGuard (*(T_g_scratchSceneGuard *)(uintptr_t)0x00048690)
typedef Screen T_g_screen;
#define g_screen (*(T_g_screen *)(uintptr_t)0x002db2b8)
typedef ImgRect T_g_splash;
#define g_splash (*(T_g_splash *)(uintptr_t)0x002db320)
typedef byte T_g_splashActive;
#define g_splashActive (*(T_g_splashActive *)(uintptr_t)0x002dc3a0)
typedef int T_g_splashRow;
#define g_splashRow (*(T_g_splashRow *)(uintptr_t)0x002db300)
typedef byte T_g_waitTapToStart;
#define g_waitTapToStart (*(T_g_waitTapToStart *)(uintptr_t)0x00048684)
typedef char T_s_100_0004352c[4];
#define s_100_0004352c (*(T_s_100_0004352c *)(uintptr_t)0x0004352c)
typedef char T_s_BMP_00043b40[4];
#define s_BMP_00043b40 (*(T_s_BMP_00043b40 *)(uintptr_t)0x00043b40)
typedef char T_s_Back_to_Menu_00043c44[13];
#define s_Back_to_Menu_00043c44 (*(T_s_Back_to_Menu_00043c44 *)(uintptr_t)0x00043c44)
typedef char T_s_D_00043bb8[2];
#define s_D_00043bb8 (*(T_s_D_00043bb8 *)(uintptr_t)0x00043bb8)
typedef char T_s_Delete_00043c10[7];
#define s_Delete_00043c10 (*(T_s_Delete_00043c10 *)(uintptr_t)0x00043c10)
typedef char T_s_EMPTY_00043bf4[6];
#define s_EMPTY_00043bf4 (*(T_s_EMPTY_00043bf4 *)(uintptr_t)0x00043bf4)
typedef char T_s_Error___00043b50[9];
#define s_Error___00043b50 (*(T_s_Error___00043b50 *)(uintptr_t)0x00043b50)
typedef char T_s_Error___More_memory_space_is_nee_00043464[38];
#define s_Error___More_memory_space_is_nee_00043464 (*(T_s_Error___More_memory_space_is_nee_00043464 *)(uintptr_t)0x00043464)
typedef char T_s_IFB_00043b3c[4];
#define s_IFB_00043b3c (*(T_s_IFB_00043b3c *)(uintptr_t)0x00043b3c)
typedef char T_s_IFJ_00043b34[4];
#define s_IFJ_00043b34 (*(T_s_IFJ_00043b34 *)(uintptr_t)0x00043b34)
typedef char T_s_IFV_00043b2c[4];
#define s_IFV_00043b2c (*(T_s_IFV_00043b2c *)(uintptr_t)0x00043b2c)
typedef char T_s_Images_logo1_jpg_000435e4[17];
#define s_Images_logo1_jpg_000435e4 (*(T_s_Images_logo1_jpg_000435e4 *)(uintptr_t)0x000435e4)
typedef char T_s_Images_logo2_jpg_000435d0[17];
#define s_Images_logo2_jpg_000435d0 (*(T_s_Images_logo2_jpg_000435d0 *)(uintptr_t)0x000435d0)
typedef char T_s_Images_logo3_jpg_000435bc[17];
#define s_Images_logo3_jpg_000435bc (*(T_s_Images_logo3_jpg_000435bc *)(uintptr_t)0x000435bc)
typedef char T_s_Images_logo4_jpg_000435a8[17];
#define s_Images_logo4_jpg_000435a8 (*(T_s_Images_logo4_jpg_000435a8 *)(uintptr_t)0x000435a8)
typedef char T_s_Images_logo5_jpg_00043594[17];
#define s_Images_logo5_jpg_00043594 (*(T_s_Images_logo5_jpg_00043594 *)(uintptr_t)0x00043594)
typedef char T_s_Images_logo6_jpg_00043580[17];
#define s_Images_logo6_jpg_00043580 (*(T_s_Images_logo6_jpg_00043580 *)(uintptr_t)0x00043580)
typedef char T_s_Images_logo7_jpg_0004356c[17];
#define s_Images_logo7_jpg_0004356c (*(T_s_Images_logo7_jpg_0004356c *)(uintptr_t)0x0004356c)
typedef char T_s_Images_logo8_jpg_00043558[17];
#define s_Images_logo8_jpg_00043558 (*(T_s_Images_logo8_jpg_00043558 *)(uintptr_t)0x00043558)
typedef char T_s_JPG_00043b38[4];
#define s_JPG_00043b38 (*(T_s_JPG_00043b38 *)(uintptr_t)0x00043b38)
typedef char T_s_Load_00043c18[5];
#define s_Load_00043c18 (*(T_s_Load_00043c18 *)(uintptr_t)0x00043c18)
typedef char T_s_Loading____00043520[12];
#define s_Loading____00043520 (*(T_s_Loading____00043520 *)(uintptr_t)0x00043520)
typedef char T_s_Loading____100_00043530[15];
#define s_Loading____100_00043530 (*(T_s_Loading____100_00043530 *)(uintptr_t)0x00043530)
typedef char T_s_Menu_smallfade_bmp_00043c80[20];
#define s_Menu_smallfade_bmp_00043c80 (*(T_s_Menu_smallfade_bmp_00043c80 *)(uintptr_t)0x00043c80)
typedef char T_s_Not_found__00043b44[12];
#define s_Not_found__00043b44 (*(T_s_Not_found__00043b44 *)(uintptr_t)0x00043b44)
typedef char T_s_OFF_00043b9c[4];
#define s_OFF_00043b9c (*(T_s_OFF_00043b9c *)(uintptr_t)0x00043b9c)
typedef char T_s_ON_00043ba0[3];
#define s_ON_00043ba0 (*(T_s_ON_00043ba0 *)(uintptr_t)0x00043ba0)
typedef char T_s_P_00043bbc[2];
#define s_P_00043bbc (*(T_s_P_00043bbc *)(uintptr_t)0x00043bbc)
typedef char T_s_Program_Files_fade__00043a88[20];
#define s_Program_Files_fade__00043a88 (*(T_s_Program_Files_fade__00043a88 *)(uintptr_t)0x00043a88)
typedef char T_s_SAVE_00043540[5];
#define s_SAVE_00043540 (*(T_s_SAVE_00043540 *)(uintptr_t)0x00043540)
typedef char T_s_SLOT_00043bec[5];
#define s_SLOT_00043bec (*(T_s_SLOT_00043bec *)(uintptr_t)0x00043bec)
typedef char T_s_STOP_00043e98[5];
#define s_STOP_00043e98 (*(T_s_STOP_00043e98 *)(uintptr_t)0x00043e98)
typedef char T_s_Save_00043c20[5];
#define s_Save_00043c20 (*(T_s_Save_00043c20 *)(uintptr_t)0x00043c20)
typedef char T_s_UI_progress_bar_gradient_jpg_00043a54[29];
#define s_UI_progress_bar_gradient_jpg_00043a54 (*(T_s_UI_progress_bar_gradient_jpg_00043a54 *)(uintptr_t)0x00043a54)
typedef char T_s_UI_progress_bar_jpg_00043a74[20];
#define s_UI_progress_bar_jpg_00043a74 (*(T_s_UI_progress_bar_jpg_00043a74 *)(uintptr_t)0x00043a74)
typedef char T_s_WAV_00043b30[4];
#define s_WAV_00043b30 (*(T_s_WAV_00043b30 *)(uintptr_t)0x00043b30)
typedef char T_s__00043bc0[2];
#define s__00043bc0 (*(T_s__00043bc0 *)(uintptr_t)0x00043bc0)
typedef char T_s__00043e8c[3];
#define s__00043e8c (*(T_s__00043e8c *)(uintptr_t)0x00043e8c)
typedef char T_s__IFJ_00043ae0[5];
#define s__IFJ_00043ae0 (*(T_s__IFJ_00043ae0 *)(uintptr_t)0x00043ae0)
typedef char T_s__Menu_Credits1_ifj_00043c6c[19];
#define s__Menu_Credits1_ifj_00043c6c (*(T_s__Menu_Credits1_ifj_00043c6c *)(uintptr_t)0x00043c6c)
typedef char T_s__Menu_Credits2_ifj_00043c58[19];
#define s__Menu_Credits2_ifj_00043c58 (*(T_s__Menu_Credits2_ifj_00043c58 *)(uintptr_t)0x00043c58)
typedef char T_s___00043a9c[2];
#define s___00043a9c (*(T_s___00043a9c *)(uintptr_t)0x00043a9c)
typedef char T_s___00043c54[2];
#define s___00043c54 (*(T_s___00043c54 *)(uintptr_t)0x00043c54)
typedef char T_s_____00043e84[5];
#define s_____00043e84 (*(T_s_____00043e84 *)(uintptr_t)0x00043e84)
typedef char T_s__fad_00043bfc[5];
#define s__fad_00043bfc (*(T_s__fad_00043bfc *)(uintptr_t)0x00043bfc)
typedef char T_s__images_End_00043ae8[12];
#define s__images_End_00043ae8 (*(T_s__images_End_00043ae8 *)(uintptr_t)0x00043ae8)
typedef char T_s_data_book_fad_00043d04[14];
#define s_data_book_fad_00043d04 (*(T_s_data_book_fad_00043d04 *)(uintptr_t)0x00043d04)
typedef char T_s_data_data_fad_00043b6c[14];
#define s_data_data_fad_00043b6c (*(T_s_data_data_fad_00043b6c *)(uintptr_t)0x00043b6c)
typedef char T_s_data_dataobjets_fad_00043cdc[20];
#define s_data_dataobjets_fad_00043cdc (*(T_s_data_dataobjets_fad_00043cdc *)(uintptr_t)0x00043cdc)
typedef char T_s_data_index_fad_00043b5c[15];
#define s_data_index_fad_00043b5c (*(T_s_data_index_fad_00043b5c *)(uintptr_t)0x00043b5c)
typedef char T_s_data_indexbook_fad_00043cf0[19];
#define s_data_indexbook_fad_00043cf0 (*(T_s_data_indexbook_fad_00043cf0 *)(uintptr_t)0x00043cf0)
typedef char T_s_data_indexobjets_fad_00043b84[21];
#define s_data_indexobjets_fad_00043b84 (*(T_s_data_indexobjets_fad_00043b84 *)(uintptr_t)0x00043b84)
typedef char T_s_fonts_FONT_POPUPS_Blanche_bmp_000439c0[30];
#define s_fonts_FONT_POPUPS_Blanche_bmp_000439c0 (*(T_s_fonts_FONT_POPUPS_Blanche_bmp_000439c0 *)(uintptr_t)0x000439c0)
typedef char T_s_fonts_FONT_POPUPS_Orange_bmp_000439a0[29];
#define s_fonts_FONT_POPUPS_Orange_bmp_000439a0 (*(T_s_fonts_FONT_POPUPS_Orange_bmp_000439a0 *)(uintptr_t)0x000439a0)
typedef char T_s_fonts_FONT_TEXTE_Blanche_bmp_00043a34[32];
#define s_fonts_FONT_TEXTE_Blanche_bmp_00043a34 (*(T_s_fonts_FONT_TEXTE_Blanche_bmp_00043a34 *)(uintptr_t)0x00043a34)
typedef char T_s_fonts_FONT_TEXTE_Bleu_bmp_000439e0[26];
#define s_fonts_FONT_TEXTE_Bleu_bmp_000439e0 (*(T_s_fonts_FONT_TEXTE_Bleu_bmp_000439e0 *)(uintptr_t)0x000439e0)
typedef char T_s_fonts_FONT_TEXTE_Jaune_bmp_000439fc[27];
#define s_fonts_FONT_TEXTE_Jaune_bmp_000439fc (*(T_s_fonts_FONT_TEXTE_Jaune_bmp_000439fc *)(uintptr_t)0x000439fc)
typedef char T_s_fonts_FONT_TEXTE_Noir_bmp_00043a18[28];
#define s_fonts_FONT_TEXTE_Noir_bmp_00043a18 (*(T_s_fonts_FONT_TEXTE_Noir_bmp_00043a18 *)(uintptr_t)0x00043a18)
typedef char T_s_images_End_00043ad4[11];
#define s_images_End_00043ad4 (*(T_s_images_End_00043ad4 *)(uintptr_t)0x00043ad4)
typedef char T_s_images__00043b7c[8];
#define s_images__00043b7c (*(T_s_images__00043b7c *)(uintptr_t)0x00043b7c)
typedef char T_s_images_thisisnot_jpg_00043b14[21];
#define s_images_thisisnot_jpg_00043b14 (*(T_s_images_thisisnot_jpg_00043b14 *)(uintptr_t)0x00043b14)
typedef char T_s_inventaire__00043cd0[12];
#define s_inventaire__00043cd0 (*(T_s_inventaire__00043cd0 *)(uintptr_t)0x00043cd0)
typedef char T_s_menu_CONTINUE_SELECT1_jpg_000434ac[26];
#define s_menu_CONTINUE_SELECT1_jpg_000434ac (*(T_s_menu_CONTINUE_SELECT1_jpg_000434ac *)(uintptr_t)0x000434ac)
typedef char T_s_menu_CONTINUE_SELECT2_jpg_000434c8[26];
#define s_menu_CONTINUE_SELECT2_jpg_000434c8 (*(T_s_menu_CONTINUE_SELECT2_jpg_000434c8 *)(uintptr_t)0x000434c8)
typedef char T_s_menu_CONTINUE_SELECT3_jpg_000434e4[26];
#define s_menu_CONTINUE_SELECT3_jpg_000434e4 (*(T_s_menu_CONTINUE_SELECT3_jpg_000434e4 *)(uintptr_t)0x000434e4)
typedef char T_s_menu_CONTINUE_SELECT4_jpg_00043500[26];
#define s_menu_CONTINUE_SELECT4_jpg_00043500 (*(T_s_menu_CONTINUE_SELECT4_jpg_00043500 *)(uintptr_t)0x00043500)
typedef char T_s_menu_Continue_jpg_00043498[18];
#define s_menu_Continue_jpg_00043498 (*(T_s_menu_Continue_jpg_00043498 *)(uintptr_t)0x00043498)
typedef char T_s_menu_Credit_SELECT1_jpg_00043768[24];
#define s_menu_Credit_SELECT1_jpg_00043768 (*(T_s_menu_Credit_SELECT1_jpg_00043768 *)(uintptr_t)0x00043768)
typedef char T_s_menu_Credit_SELECT2_jpg_00043780[24];
#define s_menu_Credit_SELECT2_jpg_00043780 (*(T_s_menu_Credit_SELECT2_jpg_00043780 *)(uintptr_t)0x00043780)
typedef char T_s_menu_Credit_SELECT3_jpg_00043798[24];
#define s_menu_Credit_SELECT3_jpg_00043798 (*(T_s_menu_Credit_SELECT3_jpg_00043798 *)(uintptr_t)0x00043798)
typedef char T_s_menu_Credit_SELECT4_jpg_000437b0[24];
#define s_menu_Credit_SELECT4_jpg_000437b0 (*(T_s_menu_Credit_SELECT4_jpg_000437b0 *)(uintptr_t)0x000437b0)
typedef char T_s_menu_Credit_jpg_00043758[16];
#define s_menu_Credit_jpg_00043758 (*(T_s_menu_Credit_jpg_00043758 *)(uintptr_t)0x00043758)
typedef char T_s_menu_Effect_FADE1_jpg_000436d0[22];
#define s_menu_Effect_FADE1_jpg_000436d0 (*(T_s_menu_Effect_FADE1_jpg_000436d0 *)(uintptr_t)0x000436d0)
typedef char T_s_menu_Effect_FADE2_jpg_000436b8[22];
#define s_menu_Effect_FADE2_jpg_000436b8 (*(T_s_menu_Effect_FADE2_jpg_000436b8 *)(uintptr_t)0x000436b8)
typedef char T_s_menu_Effect_FADE3_jpg_000436a0[22];
#define s_menu_Effect_FADE3_jpg_000436a0 (*(T_s_menu_Effect_FADE3_jpg_000436a0 *)(uintptr_t)0x000436a0)
typedef char T_s_menu_Effect_FADE4_jpg_00043688[22];
#define s_menu_Effect_FADE4_jpg_00043688 (*(T_s_menu_Effect_FADE4_jpg_00043688 *)(uintptr_t)0x00043688)
typedef char T_s_menu_Effect_GLOW1_jpg_00043670[22];
#define s_menu_Effect_GLOW1_jpg_00043670 (*(T_s_menu_Effect_GLOW1_jpg_00043670 *)(uintptr_t)0x00043670)
typedef char T_s_menu_Effect_GLOW2_jpg_00043658[24];
#define s_menu_Effect_GLOW2_jpg_00043658 (*(T_s_menu_Effect_GLOW2_jpg_00043658 *)(uintptr_t)0x00043658)
typedef char T_s_menu_Effect_GLOW3_jpg_00043640[22];
#define s_menu_Effect_GLOW3_jpg_00043640 (*(T_s_menu_Effect_GLOW3_jpg_00043640 *)(uintptr_t)0x00043640)
typedef char T_s_menu_Effect_GLOW4_jpg_00043628[22];
#define s_menu_Effect_GLOW4_jpg_00043628 (*(T_s_menu_Effect_GLOW4_jpg_00043628 *)(uintptr_t)0x00043628)
typedef char T_s_menu_Effect_GLOW5_jpg_00043610[24];
#define s_menu_Effect_GLOW5_jpg_00043610 (*(T_s_menu_Effect_GLOW5_jpg_00043610 *)(uintptr_t)0x00043610)
typedef char T_s_menu_Effect_GLOW6_jpg_000435f8[22];
#define s_menu_Effect_GLOW6_jpg_000435f8 (*(T_s_menu_Effect_GLOW6_jpg_000435f8 *)(uintptr_t)0x000435f8)
typedef char T_s_menu_LOAD_GAME_SELECT1_jpg_00043878[28];
#define s_menu_LOAD_GAME_SELECT1_jpg_00043878 (*(T_s_menu_LOAD_GAME_SELECT1_jpg_00043878 *)(uintptr_t)0x00043878)
typedef char T_s_menu_LOAD_GAME_SELECT2_jpg_00043894[27];
#define s_menu_LOAD_GAME_SELECT2_jpg_00043894 (*(T_s_menu_LOAD_GAME_SELECT2_jpg_00043894 *)(uintptr_t)0x00043894)
typedef char T_s_menu_LOAD_GAME_SELECT3_jpg_000438b0[27];
#define s_menu_LOAD_GAME_SELECT3_jpg_000438b0 (*(T_s_menu_LOAD_GAME_SELECT3_jpg_000438b0 *)(uintptr_t)0x000438b0)
typedef char T_s_menu_LOAD_GAME_SELECT4_jpg_000438cc[27];
#define s_menu_LOAD_GAME_SELECT4_jpg_000438cc (*(T_s_menu_LOAD_GAME_SELECT4_jpg_000438cc *)(uintptr_t)0x000438cc)
typedef char T_s_menu_Load_Game_jpg_00043864[19];
#define s_menu_Load_Game_jpg_00043864 (*(T_s_menu_Load_Game_jpg_00043864 *)(uintptr_t)0x00043864)
typedef char T_s_menu_MENU_BACKGROUND_jpg_0004396c[25];
#define s_menu_MENU_BACKGROUND_jpg_0004396c (*(T_s_menu_MENU_BACKGROUND_jpg_0004396c *)(uintptr_t)0x0004396c)
typedef char T_s_menu_Menu_saveload_jpg_00043988[23];
#define s_menu_Menu_saveload_jpg_00043988 (*(T_s_menu_Menu_saveload_jpg_00043988 *)(uintptr_t)0x00043988)
typedef char T_s_menu_NEW_GAME_SELECT1_jpg_000438fc[26];
#define s_menu_NEW_GAME_SELECT1_jpg_000438fc (*(T_s_menu_NEW_GAME_SELECT1_jpg_000438fc *)(uintptr_t)0x000438fc)
typedef char T_s_menu_NEW_GAME_SELECT2_jpg_00043918[26];
#define s_menu_NEW_GAME_SELECT2_jpg_00043918 (*(T_s_menu_NEW_GAME_SELECT2_jpg_00043918 *)(uintptr_t)0x00043918)
typedef char T_s_menu_NEW_GAME_SELECT3_jpg_00043934[26];
#define s_menu_NEW_GAME_SELECT3_jpg_00043934 (*(T_s_menu_NEW_GAME_SELECT3_jpg_00043934 *)(uintptr_t)0x00043934)
typedef char T_s_menu_NEW_GAME_SELECT4_jpg_00043950[26];
#define s_menu_NEW_GAME_SELECT4_jpg_00043950 (*(T_s_menu_NEW_GAME_SELECT4_jpg_00043950 *)(uintptr_t)0x00043950)
typedef char T_s_menu_New_Game_jpg_000438e8[18];
#define s_menu_New_Game_jpg_000438e8 (*(T_s_menu_New_Game_jpg_000438e8 *)(uintptr_t)0x000438e8)
typedef char T_s_menu_QUIT_SELECT1_jpg_000436f8[22];
#define s_menu_QUIT_SELECT1_jpg_000436f8 (*(T_s_menu_QUIT_SELECT1_jpg_000436f8 *)(uintptr_t)0x000436f8)
typedef char T_s_menu_QUIT_SELECT2_jpg_00043710[22];
#define s_menu_QUIT_SELECT2_jpg_00043710 (*(T_s_menu_QUIT_SELECT2_jpg_00043710 *)(uintptr_t)0x00043710)
typedef char T_s_menu_QUIT_SELECT3_jpg_00043728[22];
#define s_menu_QUIT_SELECT3_jpg_00043728 (*(T_s_menu_QUIT_SELECT3_jpg_00043728 *)(uintptr_t)0x00043728)
typedef char T_s_menu_QUIT_SELECT4_jpg_00043740[22];
#define s_menu_QUIT_SELECT4_jpg_00043740 (*(T_s_menu_QUIT_SELECT4_jpg_00043740 *)(uintptr_t)0x00043740)
typedef char T_s_menu_SAVE_GAME_SELECT1_jpg_000437f4[27];
#define s_menu_SAVE_GAME_SELECT1_jpg_000437f4 (*(T_s_menu_SAVE_GAME_SELECT1_jpg_000437f4 *)(uintptr_t)0x000437f4)
typedef char T_s_menu_SAVE_GAME_SELECT2_jpg_00043810[28];
#define s_menu_SAVE_GAME_SELECT2_jpg_00043810 (*(T_s_menu_SAVE_GAME_SELECT2_jpg_00043810 *)(uintptr_t)0x00043810)
typedef char T_s_menu_SAVE_GAME_SELECT3_jpg_0004382c[27];
#define s_menu_SAVE_GAME_SELECT3_jpg_0004382c (*(T_s_menu_SAVE_GAME_SELECT3_jpg_0004382c *)(uintptr_t)0x0004382c)
typedef char T_s_menu_SAVE_GAME_SELECT4_jpg_00043848[27];
#define s_menu_SAVE_GAME_SELECT4_jpg_00043848 (*(T_s_menu_SAVE_GAME_SELECT4_jpg_00043848 *)(uintptr_t)0x00043848)
typedef char T_s_menu_quit_jpg_000436e8[14];
#define s_menu_quit_jpg_000436e8 (*(T_s_menu_quit_jpg_000436e8 *)(uintptr_t)0x000436e8)
typedef char T_s_menu_save_game_OFF_jpg_000437dc[24];
#define s_menu_save_game_OFF_jpg_000437dc (*(T_s_menu_save_game_OFF_jpg_000437dc *)(uintptr_t)0x000437dc)
typedef char T_s_menu_save_game_jpg_000437c8[19];
#define s_menu_save_game_jpg_000437c8 (*(T_s_menu_save_game_jpg_000437c8 *)(uintptr_t)0x000437c8)
typedef char T_s_menu_scroll_jpg_00043548[16];
#define s_menu_scroll_jpg_00043548 (*(T_s_menu_scroll_jpg_00043548 *)(uintptr_t)0x00043548)
typedef char T_s_save_save_00043c04[10];
#define s_save_save_00043c04 (*(T_s_save_save_00043c04 *)(uintptr_t)0x00043c04)
typedef char T_s_sounds_PowerOn_wav_00043bd8[19];
#define s_sounds_PowerOn_wav_00043bd8 (*(T_s_sounds_PowerOn_wav_00043bd8 *)(uintptr_t)0x00043bd8)
typedef char T_s_sounds__00043e90[8];
#define s_sounds__00043e90 (*(T_s_sounds__00043e90 *)(uintptr_t)0x00043e90)
typedef char T_s_sounds_bruit_plastic_wav_00043c28[25];
#define s_sounds_bruit_plastic_wav_00043c28 (*(T_s_sounds_bruit_plastic_wav_00043c28 *)(uintptr_t)0x00043c28)
typedef char T_s_sounds_feuilletter_wav_00043e6c[23];
#define s_sounds_feuilletter_wav_00043e6c (*(T_s_sounds_feuilletter_wav_00043e6c *)(uintptr_t)0x00043e6c)
typedef char T_s_space[2];
#define s_space (*(T_s_space *)(uintptr_t)0x0004351c)
typedef char T_s_sprites__00043ba4[9];
#define s_sprites__00043ba4 (*(T_s_sprites__00043ba4 *)(uintptr_t)0x00043ba4)
typedef char T_s_ui_FlecheDownOFF_jpg_00043d28[21];
#define s_ui_FlecheDownOFF_jpg_00043d28 (*(T_s_ui_FlecheDownOFF_jpg_00043d28 *)(uintptr_t)0x00043d28)
typedef char T_s_ui_FlecheDownON_jpg_00043d14[20];
#define s_ui_FlecheDownON_jpg_00043d14 (*(T_s_ui_FlecheDownON_jpg_00043d14 *)(uintptr_t)0x00043d14)
typedef char T_s_ui_FlecheUpOFF_jpg_00043d54[20];
#define s_ui_FlecheUpOFF_jpg_00043d54 (*(T_s_ui_FlecheUpOFF_jpg_00043d54 *)(uintptr_t)0x00043d54)
typedef char T_s_ui_FlecheUpON_jpg_00043d40[18];
#define s_ui_FlecheUpON_jpg_00043d40 (*(T_s_ui_FlecheUpON_jpg_00043d40 *)(uintptr_t)0x00043d40)
typedef char T_s_ui_PopUpAller_jpg_00043bc4[18];
#define s_ui_PopUpAller_jpg_00043bc4 (*(T_s_ui_PopUpAller_jpg_00043bc4 *)(uintptr_t)0x00043bc4)
typedef char T_s_ui_UIAction_bmp_00043e38[16];
#define s_ui_UIAction_bmp_00043e38 (*(T_s_ui_UIAction_bmp_00043e38 *)(uintptr_t)0x00043e38)
typedef char T_s_ui_UIText_bmp_00043e48[14];
#define s_ui_UIText_bmp_00043e48 (*(T_s_ui_UIText_bmp_00043e48 *)(uintptr_t)0x00043e48)
typedef char T_s_ui_UIinv_bmp_00043e28[13];
#define s_ui_UIinv_bmp_00043e28 (*(T_s_ui_UIinv_bmp_00043e28 *)(uintptr_t)0x00043e28)
typedef char T_s_ui_UiAllerOFF_bmp_00043d7c[18];
#define s_ui_UiAllerOFF_bmp_00043d7c (*(T_s_ui_UiAllerOFF_bmp_00043d7c *)(uintptr_t)0x00043d7c)
typedef char T_s_ui_UiAllerON_bmp_00043d68[17];
#define s_ui_UiAllerON_bmp_00043d68 (*(T_s_ui_UiAllerON_bmp_00043d68 *)(uintptr_t)0x00043d68)
typedef char T_s_ui_UiBookOFF_bmp_00043dc0[20];
#define s_ui_UiBookOFF_bmp_00043dc0 (*(T_s_ui_UiBookOFF_bmp_00043dc0 *)(uintptr_t)0x00043dc0)
typedef char T_s_ui_UiBookON_bmp_00043db0[16];
#define s_ui_UiBookON_bmp_00043db0 (*(T_s_ui_UiBookON_bmp_00043db0 *)(uintptr_t)0x00043db0)
typedef char T_s_ui_UiInvOFF_bmp_00043da0[16];
#define s_ui_UiInvOFF_bmp_00043da0 (*(T_s_ui_UiInvOFF_bmp_00043da0 *)(uintptr_t)0x00043da0)
typedef char T_s_ui_UiInvON_bmp_00043d90[16];
#define s_ui_UiInvON_bmp_00043d90 (*(T_s_ui_UiInvON_bmp_00043d90 *)(uintptr_t)0x00043d90)
typedef char T_s_ui_UiOptionsOFF_bmp_00043de8[20];
#define s_ui_UiOptionsOFF_bmp_00043de8 (*(T_s_ui_UiOptionsOFF_bmp_00043de8 *)(uintptr_t)0x00043de8)
typedef char T_s_ui_UiOptionsON_bmp_00043dd4[19];
#define s_ui_UiOptionsON_bmp_00043dd4 (*(T_s_ui_UiOptionsON_bmp_00043dd4 *)(uintptr_t)0x00043dd4)
typedef char T_s_ui_Zoom_Mask_bmp_00043e58[17];
#define s_ui_Zoom_Mask_bmp_00043e58 (*(T_s_ui_Zoom_Mask_bmp_00043e58 *)(uintptr_t)0x00043e58)
typedef char T_s_ui_book_bmp_00043e1c[12];
#define s_ui_book_bmp_00043e1c (*(T_s_ui_book_bmp_00043e1c *)(uintptr_t)0x00043e1c)
typedef char T_s_ui_inventaire_jpg_00043e08[18];
#define s_ui_inventaire_jpg_00043e08 (*(T_s_ui_inventaire_jpg_00043e08 *)(uintptr_t)0x00043e08)
typedef char T_s_ui_ui_bmp_00043dfc[10];
#define s_ui_ui_bmp_00043dfc (*(T_s_ui_ui_bmp_00043dfc *)(uintptr_t)0x00043dfc)
typedef char T_s_zoom__00043bb0[6];
#define s_zoom__00043bb0 (*(T_s_zoom__00043bb0 *)(uintptr_t)0x00043bb0)
typedef wchar16 T_u_Error_SaveFile_is_not_valid___00043c94[30];
#define u_Error_SaveFile_is_not_valid___00043c94 (*(T_u_Error_SaveFile_is_not_valid___00043c94 *)(uintptr_t)0x00043c94)
typedef wchar16 T_u_FADE_0004348c[5];
#define u_FADE_0004348c (*(T_u_FADE_0004348c *)(uintptr_t)0x0004348c)
typedef wchar16 T_u_Fade_00043458[5];
#define u_Fade_00043458 (*(T_u_Fade_00043458 *)(uintptr_t)0x00043458)
typedef wchar16 T_u_Gamma_00043b08[6];
#define u_Gamma_00043b08 (*(T_u_Gamma_00043b08 *)(uintptr_t)0x00043b08)
typedef wchar16 T_u_Install_Dir_00043aa0[12];
#define u_Install_Dir_00043aa0 (*(T_u_Install_Dir_00043aa0 *)(uintptr_t)0x00043aa0)
typedef wchar16 T_u_SOFTWARE_Fade_00043ab8[14];
#define u_SOFTWARE_Fade_00043ab8 (*(T_u_SOFTWARE_Fade_00043ab8 *)(uintptr_t)0x00043ab8)
typedef wchar16 T_u_TilipTip_00043af4[9];
#define u_TilipTip_00043af4 (*(T_u_TilipTip_00043af4 *)(uintptr_t)0x00043af4)
